log_level = "warn"
outputs = "All"
position = "Top"
# App launcher command, it will be used to open the launcher,
# without a value the related button will not appear
# optional, default None
app_launcher_cmd = "~/.config/rofi/launcher.sh"
# Clipboard command, it will be used to open the clipboard menu,
# without a value the related button will not appear
# optional, default None
clipboard_cmd = "cliphist-rofi-img | wl-copy"

# Declare which modules should be used and in which position in the status bar.
# This is the list of all possible modules
#  - AppLauncher
#  - Updates
#  - Clipboard
#  - Workspaces
#  - WindowTitle
#  - SystemInfo
#  - KeyboardLayout
#  - KeyboardSubmap
#  - Tray
#  - Clock
#  - Privacy
#  - MediaPlayer
#  - Settings
# optional, the following is the default configuration
[modules]
left = ["Workspaces", "WindowTitle"]
center = ["Clock", "MediaPlayer"]
right = ["KeyboardLayout", "SystemInfo", "Settings"]

# Update module configuration.
# Without a value the related button will not appear.
# optional, default None
[updates]
# The check command will be used to retrieve the update list.
# It should return something like `package_name version_from -> version_to\n`
check_cmd = "checkupdates; paru -Qua"
# The update command is used to init the OS update process
update_cmd = 'alacritty -e bash -c "paru; echo Done - Press enter to exit; read" &'

[workspaces]
visibility_mode = "All"

[window_title]
mode = "Title"
truncate_title_after_length = 150

# keyboardLayout module configuration
# Names can be found in `hyprctl devices | grep "active keymap"`
[keyboard_layout.labels]
"English (US)" = "US"
"Persian (Windows)" = "FA"

[system]
# The possible values are:
#  - Cpu
#  - Memory
#  - MemorySwap
#  - Temperature
#  - { disk = "path" }
#  - IpAddress
#  - DownloadSpeed
#  - UploadSpeed
indicators = ["Temperature"]

[system.cpu]
warn_threshold = 60
alert_threshold = 80

[system.memory]
warn_threshold = 70
alert_threshold = 85

[system.temperature]
warn_threshold = 60
alert_threshold = 80

[system.disk]
warn_threshold = 80
alert_threshold = 90

[clock]
# clock format see: https://docs.rs/chrono/latest/chrono/format/strftime/index.html
format = "%R"

[media_player]
max_title_length = 100

[settings]
# lock_cmd = "hyprlock &"
shutdown_cmd = "shutdown now"
suspend_cmd = "systemctl suspend"
reboot_cmd = "systemctl reboot"
logout_cmd = "loginctl kill-user $(whoami)"
audio_sinks_more_cmd = "pavucontrol -t 3"
audio_sources_more_cmd = "pavucontrol -t 4"
wifi_more_cmd = "nm-connection-editor"
vpn_more_cmd = "nm-connection-editor"
bluetooth_more_cmd = "blueman-manager"
remove_airplane_btn = true

[appearance]
font_name = "Fira Code Nerd Font"
style = "Solid"
opacity = 1
background_color = "#000"
primary_color = "#6ea3e3ff"
secondary_color = "#000"
success_color = "#bef264"
danger_color = "#f38ba8"
text_color = "#98c6ff"
workspace_colors = ["#94e2d5"]

[appearance.menu]
opacity = 1
backdrop = 0
